[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = ".netlify/functions"
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200